# Generated by Django 3.1.3 on 2020-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('test_standard', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=50)),
            ],
        ),
    ]
